DROP INDEX IF EXISTS Friend_IdxA;
DROP INDEX IF EXISTS Friend_IdxB;
DROP INDEX IF EXISTS Message_Idx;

CREATE INDEX Friend_IdxA
ON FRIENDS
USING BTREE (userA);

CREATE INDEX Friend_IdxB
ON FRIENDS
USING BTREE (userB);

CREATE INDEX Message_Idx
ON MESSAGE
USING BTREE (msgId, status);